### ISSUE TITLE
Running a Local Version

### ISSUE THREAD

**Issue by Sattishh** [Oliver-Akins/top-lists#33]
I was wondering If I could get some steps on how I can try this out since it's a really interesting repository and run it in my local host. Hopefully you could help me with this. Thanks 

-Sattish

**Comment by Oliver-Akins** [comment]
Hi,

Thanks for your interest in this repository.

After cloning the repo, you can get a development version running quite easily by running either `pnpm install` or `npm install` and then `pnpm serve` or `npm serve`.

You should also change the client ID in [this file](https://www.github.com/Oliver-Akins/top-lists/tree/main/src%2Fcomponents%2FLoginView.vue) to be an app registered in [Spotify's dev dashboard](https://developer.spotify.com/dashboard/applications) that is under your control.

Hopefully this helped! I'll get some better instructions put together in the readme later today. If you have any other questions just let me know

**Comment by Oliver-Akins** [comment]
@Sattishh -> I have since added more detailed instructions to the README on the main branch, if you have any questions that aren't addressed by the README let me know so that I can add them as relevant.

**Comment by Sattishh** [comment]
Thanks a lot, I was actually going to use this repository as a base for my website and change few things to my liking, I would need to credit you and link to this repository according to the License right?

**Comment by Oliver-Akins** [comment]
I'm going to be up front, I'm not a lawyer, I don't have a lawyer for this project, I just made it for fun, so the license isn't really at the forefront of my mind.

So as long as you do the following I won't be pursuing anything in regards to the license:
 - link back to this repository
 - clearly state any significant changes to it
 - keep the source under GNU's GPL 3

Beyond that, I'm just happy that other people can find a use for this code as I do. And I'd love to see how you use the codebase when you get your stuff running (though not absolutely necessary).

And if you like the repo I'd greatly appreciate a star, though by all means only if you actually want to and would like to support my efforts with this project, as starring is a simple way of supporting that costs absolutely nothing.

(**Obligatory Note To People Reading This Issue in the Future**: This enforcement is subject to change and may not be the same when you go to create a derivative work, best bet, follow the license as closely as possible, if you want to ask about something feel free to open an issue and we can discuss your specific use case)

**Comment by Sattishh** [comment]
Gotcha.
